### ISSUE TITLE
[backend] if user has no friends return null

### ISSUE THREAD

**Issue by oleksandran** [adrianosela/mapp#176]
-currently returns 500

**Comment by israeltq** [comment]
Which call is this?

**Comment by oleksandran** [comment]
"/user/following" @israeltq

**Comment by israeltq** [comment]
Hmm, it should return an empty array. I'll debug and fix it thanks

**Comment by israeltq** [comment]
Oh, actually I think this is because the latest changes haven't been deployed yet. @adrianosela was my PR this morning already deployed on prod??

**Comment by adrianosela** [comment]
no @israeltq , deploying now

**Comment by israeltq** [comment]
Thanks @adrianosela . @oleksandran close the issue if this is resolved after deployment. Thanks
